version: '3'
services:
  online-shopping-api:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    image: online-shopping-api
    container_name: online-shopping-api
    restart: always
    ports:
      - '3150:3000'
    volumes:
      - ./logs:/usr/src/app/logs
