enum ConfigKey {
    NODE_ENV = 'NODE_ENV',
    PORT = 'PORT',
    VERSION = 'VERSION',
    BASE_PATH = 'BASE_PATH',
    CORS_WHITELIST = 'CORS_WHITELIST',
    LOG_LEVEL = 'LOG_LEVEL',
    LOG_ROOT_FOLDER = 'LOG_ROOT_FOLDER',
    JWT_ACCESS_TOKEN_SECRET_KEY = 'JWT_ACCESS_TOKEN_SECRET_KEY',
    JWT_ACCESS_TOKEN_EXPIRED_IN = 'JWT_ACCESS_TOKEN_EXPIRED_IN',
    JWT_REFRESH_TOKEN_SECRET_KEY = 'JWT_REFRESH_TOKEN_SECRET_KEY',
    JWT_REFRESH_TOKEN_EXPIRED_IN = 'JWT_REFRESH_TOKEN_EXPIRED_IN',
    //google-login config keys
    GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
    GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
    // mysql
    MYSQL_HOST = 'MYSQL_HOST',
    MYSQL_PORT = 'MYSQL_PORT',
    MYSQL_USER = 'MYSQL_USER',
    MYSQL_PASSWORD = 'MYSQL_PASSWORD',
    MYSQL_DATABASE_NAME = 'MYSQL_DATABASE_NAME',
    MYSQL_CONNECTION_LIMIT = 'MYSQL_CONNECTION_LIMIT',
    MYSQL_CONNECTION_RATE_LIMIT = 'MYSQL_CONNECTION_RATE_LIMIT',
    MYSQL_DEBUG_MODE = 'MYSQL_DEBUG_MODE',
    // sendgirid
    SENDGRID_API_KEY = 'SENDGRID_API_KEY',
    SENDGRID_API_HOST = 'SENDGRID_API_HOST',
    SENDGRID_SENDER_EMAIL = 'SENDGRID_SENDER_EMAIL',
    RESET_PASSWORD_OTP_EXPIRED_IN = 'RESET_PASSWORD_OTP_EXPIRED_IN',
    REGISTER_USER_OTP_EXPIRED_IN = 'REGISTER_USER_OTP_EXPIRED_IN',
}

export default ConfigKey;
