name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: [self-hosted, windows, X64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: ls
  check-eks-pods-info:
    runs-on: [self-hosted, linux, X64]
    steps:
      - run: k cluster-info
      - run: k get pods
